# Generated by Django 4.1 on 2022-10-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
    ]
