# Generated by Django 4.1 on 2022-10-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
    ]
